"""Tune scoring parameters on the dev eval set (hold-out labels) and write a report.

Grid-searches flag_threshold, flow.share_saturation and hop_decay by rescoring each
wallet's graph (built once, from cache). Selection rule, fixed before looking at results:
maximize F1 subject to flagging at most MAX_FPR of negatives; ties go to the more
conservative setting (higher threshold, larger saturation, stronger hop decay).

Only the dev set is used here. Final numbers come from a fresh test set scored once
with the chosen parameters (scripts/run_eval.py), so they aren't tuned on.

Usage: docker compose run --rm backend python scripts/tune.py [--version v1]
"""

import argparse
import asyncio
import itertools
from dataclasses import dataclass
from pathlib import Path

from app.config import ScoringParams, load_scoring_params
from app.db.session import get_engine
from app.services.eval_runner import build_graphs, label_index
from app.services.evaluation import EvalSet, confusion
from app.services.scoring import score_graph

REPO = Path(__file__).resolve().parents[2]
EVAL_DIR = REPO / "data" / "eval"
THRESHOLDS = [1.0, 2.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 40.0, 50.0]
SATURATIONS = [0.01, 0.02, 0.05, 0.10, 0.20]
HOP_DECAYS = [0.5, 0.75, 1.0]
MAX_FPR = 0.02


@dataclass(frozen=True)
class Trial:
    threshold: float
    saturation: float
    hop_decay: float
    precision: float
    recall: float
    f1: float
    fpr: float
    tp: int
    fp: int

    @property
    def conservativeness(self) -> tuple[float, float, float]:
        return (self.threshold, self.saturation, -self.hop_decay)


def with_params(params: ScoringParams, saturation: float, hop_decay: float) -> ScoringParams:
    flow = params.flow.model_copy(update={"share_saturation": saturation})
    return params.model_copy(update={"flow": flow, "hop_decay": hop_decay})


async def main(version: str) -> None:
    eval_set = EvalSet.from_json((EVAL_DIR / f"eval_set_{version}.json").read_text())
    params = load_scoring_params()
    run = await build_graphs(
        eval_set, label_index(eval_set, "holdout"), params.graph, params, name="dev"
    )
    await get_engine().dispose()
    examples = [e for e in eval_set.examples if e.address in run.graphs]
    labels = [e.label for e in examples]

    trials = []
    for saturation, hop_decay in itertools.product(SATURATIONS, HOP_DECAYS):
        variant = with_params(params, saturation, hop_decay)
        scores = [score_graph(run.graphs[e.address], variant).score for e in examples]
        for threshold in THRESHOLDS:
            c = confusion(scores, labels, threshold)
            trials.append(
                Trial(
                    threshold, saturation, hop_decay, c.precision, c.recall, c.f1,
                    c.false_positive_rate, c.tp, c.fp,
                )
            )  # fmt: skip

    eligible = [t for t in trials if t.fpr <= MAX_FPR]
    best = max(eligible, key=lambda t: (round(t.f1, 6), t.conservativeness))
    current = next(
        t
        for t in trials
        if (t.threshold, t.saturation, t.hop_decay)
        == (params.flag_threshold, params.flow.share_saturation, params.hop_decay)
    )

    lines = [
        f"# Tuning on dev set {version}",
        "",
        "Generated by `backend/scripts/tune.py`; do not edit by hand. Reproduce with:",
        "",
        "```bash",
        f"docker compose run --rm backend python scripts/tune.py --version {version}",
        "```",
        "",
        f"Hold-out labels, N = {len(examples)} ({sum(labels)} positive). Selection rule "
        f"(fixed in advance): maximize F1 with false-positive rate ≤ {MAX_FPR:.0%}; ties go "
        "to the more conservative setting. These numbers are *tuned on this set*; quote "
        "the test-set results in `docs/EVALUATION.md` instead.",
        "",
        "| | flag_threshold | share_saturation | hop_decay | Precision | Recall | F1 | FPR |",
        "|---|---|---|---|---|---|---|---|",
    ]

    def row(name: str, t: Trial) -> str:
        return (
            f"| {name} | {t.threshold:g} | {t.saturation:g} | {t.hop_decay:g} | "
            f"{t.precision:.1%} | {t.recall:.1%} | {t.f1:.3f} | {t.fpr:.1%} |"
        )

    lines += [row("**chosen**", best), row("before tuning", current), ""]
    lines += [
        "Top 15 eligible settings:",
        "",
        "| flag_threshold | share_saturation | hop_decay | Precision | Recall | F1 | FPR |",
        "|---|---|---|---|---|---|---|",
    ]
    for t in sorted(eligible, key=lambda t: (-t.f1, t.conservativeness))[:15]:
        lines.append(row("", t).removeprefix("|  "))
    (REPO / "docs" / "evaluation" / f"tuning_{version}.md").write_text("\n".join(lines) + "\n")

    print(f"Chosen: flag_threshold={best.threshold:g}, share_saturation={best.saturation:g}, "
          f"hop_decay={best.hop_decay:g}  (F1 {best.f1:.3f}, precision {best.precision:.1%}, "
          f"recall {best.recall:.1%}, FPR {best.fpr:.1%})")  # fmt: skip
    print(f"Before:  F1 {current.f1:.3f}, recall {current.recall:.1%}")
    print(f"Wrote docs/evaluation/tuning_{version}.md")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", default="v1")
    asyncio.run(main(parser.parse_args().version))
