"""Add flagged to score_runs

Revision ID: 02baf98c66ab
Revises: 7602b7f5dd67
Create Date: 2026-09-27 17:54:11.062000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '02baf98c66ab'
down_revision: str | None = '7602b7f5dd67'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_runs', sa.Column('flagged', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_runs', 'flagged')
    # ### end Alembic commands ###
