"""Add calls_avoided to api_metrics

Revision ID: 2dac893506f9
Revises: 55490f655df7
Create Date: 2026-09-24 14:39:57.448402

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2dac893506f9'
down_revision: str | None = '55490f655df7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_metrics', sa.Column('calls_avoided', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_metrics', 'calls_avoided')
    # ### end Alembic commands ###
