"""Add transactions, fetch_log, api_metrics tables

Revision ID: 55490f655df7
Revises: 
Create Date: 2026-09-24 14:20:32.062758

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '55490f655df7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.BigInteger(), nullable=False),
    sa.Column('upstream_calls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fetch_log',
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_block', sa.BigInteger(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('address', 'endpoint')
    )
    op.create_index('ix_fetch_log_address_endpoint', 'fetch_log', ['address', 'endpoint'], unique=False)
    op.create_table('transactions',
    sa.Column('hash', sa.String(length=66), nullable=False),
    sa.Column('from_addr', sa.String(length=42), nullable=False),
    sa.Column('to_addr', sa.String(length=42), nullable=False),
    sa.Column('value_wei', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('source_endpoint', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index('ix_transactions_from_addr', 'transactions', ['from_addr'], unique=False)
    op.create_index('ix_transactions_to_addr', 'transactions', ['to_addr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_to_addr', table_name='transactions')
    op.drop_index('ix_transactions_from_addr', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_fetch_log_address_endpoint', table_name='fetch_log')
    op.drop_table('fetch_log')
    op.drop_table('api_metrics')
    # ### end Alembic commands ###
