"""Add score_runs table

Revision ID: 7602b7f5dd67
Revises: a329ab82a7c8
Create Date: 2026-09-26 01:10:38.774760

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7602b7f5dd67'
down_revision: str | None = 'a329ab82a7c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params_hash', sa.String(length=12), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('bucket', sa.String(length=16), nullable=True),
    sa.Column('breakdown_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('graph_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'done', 'failed')", name='ck_score_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_score_runs_address_params_created', 'score_runs', ['address', 'params_hash', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_score_runs_address_params_created', table_name='score_runs')
    op.drop_table('score_runs')
    # ### end Alembic commands ###
