"""Add address_labels table

Revision ID: 833647c80257
Revises: 2dac893506f9
Create Date: 2026-09-24 15:13:34.687981

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '833647c80257'
down_revision: str | None = '2dac893506f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_labels',
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('label_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("label_type IN ('sanctioned', 'malicious', 'exchange', 'mixer')", name='ck_address_labels_label_type'),
    sa.CheckConstraint('severity IS NULL OR (severity >= 0 AND severity <= 1)', name='ck_address_labels_severity'),
    sa.PrimaryKeyConstraint('address', 'label_type')
    )
    op.create_index('ix_address_labels_source', 'address_labels', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_address_labels_source', table_name='address_labels')
    op.drop_table('address_labels')
    # ### end Alembic commands ###
